<?php

return [
  'ctrl' => [
    'label' => 'title',
    'descriptionColumn' => 'rowDescription',
    'tstamp' => 'tstamp',
    'sortby' => 'sorting',
    'title' => 'LLL:EXT:core/Resources/Private/Language/locallang_tca.xlf:pages',
    'type' => 'doktype',
    'versioningWS' => true,
    'delete' => 'deleted',
    'crdate' => 'crdate',
    'hideAtCopy' => true,
    'prependAtCopy' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.prependAtCopy',
    'editlock' => 'editlock',
    'useColumnsForDefaultValues' => 'doktype,fe_group,hidden',
    'languageField' => 'sys_language_uid',
    'transOrigPointerField' => 'l10n_parent',
    'transOrigDiffSourceField' => 'l10n_diffsource',
    'translationSource' => 'l10n_source',
    'enablecolumns' => [
      'disabled' => 'hidden',
      'starttime' => 'starttime',
      'endtime' => 'endtime',
      'fe_group' => 'fe_group',
    ],
    'typeicon_column' => 'doktype',
    'typeicon_classes' => [
      '1' => 'apps-pagetree-page-default',
      '1-hideinmenu' => 'apps-pagetree-page-hideinmenu',
      '1-root' => 'apps-pagetree-page-domain',
      '3' => 'apps-pagetree-page-shortcut-external',
      '3-hideinmenu' => 'apps-pagetree-page-shortcut-external-hideinmenu',
      '3-root' => 'apps-pagetree-page-shortcut-external-root',
      '4' => 'apps-pagetree-page-shortcut',
      '4-hideinmenu' => 'apps-pagetree-page-shortcut-hideinmenu',
      '4-root' => 'apps-pagetree-page-shortcut-root',
      '6' => 'apps-pagetree-page-backend-users',
      '6-hideinmenu' => 'apps-pagetree-page-backend-users-hideinmenu',
      '6-root' => 'apps-pagetree-page-backend-users-root',
      '7' => 'apps-pagetree-page-mountpoint',
      '7-hideinmenu' => 'apps-pagetree-page-mountpoint-hideinmenu',
      '7-root' => 'apps-pagetree-page-mountpoint-root',
      '199' => 'apps-pagetree-spacer',
      '199-hideinmenu' => 'apps-pagetree-spacer-hideinmenu',
      '199-root' => 'apps-pagetree-page-domain',
      '254' => 'apps-pagetree-folder-default',
      '254-hideinmenu' => 'apps-pagetree-folder-default',
      '254-root' => 'apps-pagetree-page-domain',
      'contains-shop' => 'apps-pagetree-folder-contains-shop',
      'contains-approve' => 'apps-pagetree-folder-contains-approve',
      'contains-fe_users' => 'apps-pagetree-folder-contains-fe_users',
      'contains-board' => 'apps-pagetree-folder-contains-board',
      'contains-news' => 'apps-pagetree-folder-contains-news',
      'page-contentFromPid' => 'apps-pagetree-page-content-from-page',
      'page-contentFromPid-root' => 'apps-pagetree-page-content-from-page-root',
      'page-contentFromPid-hideinmenu' => 'apps-pagetree-page-content-from-page-hideinmenu',
      'default' => 'apps-pagetree-page-default',
    ],
    // Will be filled automatically, if ctrl.security.ignorePageTypeRestrictions is enabled for a table.
    'defaultAllowedRecordTypes' => [],
  ],
  // ...
];
