# Settings.yml
---
conf.py:
  project: TSconfig Reference
  copyright: 2000-2015
  version: 7
  release: 7
  intersphinx_mapping:
    t3tsref:
    - https://docs.typo3.org/typo3cms/TyposcriptReference
    - null
    t3tssyntax:
    - https://docs.typo3.org/typo3cms/TyposcriptSyntaxReference
    - null
    t3api:
    - https://docs.typo3.org/typo3cms/CoreApiReference
    - null
    t3tca:
    - https://docs.typo3.org/typo3cms/TCAReference
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-TSconfig
    github_branch: latest
  latex_documents:
  - - Index
    - t3tsconfig.tex
    - TSconfig Reference
    - Documentation Team
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}

...
