name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    permissions:
      contents: write        # needed to push the backport branch
      pull-requests: write   # needed to open the PR
    steps:
      - name: Backport
        uses: m-kuhn/backport@beacefbdb02ada95eb88dd9935599945ec776b73
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
